<?php

namespace AppBundle\Repository;

/**
 * DepictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepictRepository extends \Doctrine\ORM\EntityRepository
{
}
