user:
    resource: "@UserBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

entities:
    type:     rest
    resource: AppBundle\Controller\EntityController

logs:
    type:     rest
    resource: AppBundle\Controller\LogController

ranks:
    type:     rest
    resource: AppBundle\Controller\RankController

users:
    type:     rest
    resource: UserBundle\Controller\UserController

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
