data:
    resource: "@DataBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

entities:
    type:     rest
    resource: DataBundle\Controller\EntityController
