app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

entities:
    type:     rest
    resource: AppBundle\Controller\EntityController

logs:
    type:     rest
    resource: AppBundle\Controller\LogController

ranks:
    type:     rest
    resource: AppBundle\Controller\RankController
